### ISSUE TITLE
[Request] Can I add this to my workshop addon?

### ISSUE THREAD

**Issue by WolfeStrider** [gabrie155/cap-shield-core-fixed#1]
May I add this to my workshop addon so people who don't know about this or how to use GitHub at all or are to lazy to can enjoy the benefits of having the shield core fixed? I'll add you as a contributor to the workshop page of course if your interested. This is my fork if you want to make a pull request: https://github.com/wolfestridershooter/cap-workshop

**Comment by gabrie155** [comment]
@wolfestridershooter absolutely! i dont mind at all!

**Comment by gabrie155** [comment]
@wolfestridershooter sure, you can add me as contributor if you'd like, heck, ill be more then happy to maintain it.

**Comment by WolfeStrider** [comment]
Thanks, sounds great!
